name: Dbt_demo
profile: snowflake
version: '4.1'
require-dbt-version: ['>=0.14.0', '<0.20.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
    hash: 'MD5'
    
models:
  Dbt_demo:
    raw_stage:
      schema: 'RAW'
      tags:
        - 'raw'
      materialized: view
    stage: 
      schema: 'STG'
      tags:
        - 'stage'
      enabled: true
      materialized: view
    raw_vault:
      schema: 'RAW_VLT'
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite' 
      

  
