version: 2

sources:
  - name: tpch_sample
    database: DATAVAULTDEMO
    schema: SRC_SIMILAR
    tables:
      - name: SUPPLIERS
      - name: PRODUCTS
      - name: ORDERS
      - name: SHIPPERS
      - name: CUSTOMERS

