version: 2

sources:
  - name: tpch_sample
    database: DATAVAULTDEMO
    schema: TARGET
    tables:
      - name: SUPPLIERS
      - name: PRODUCTS
      - name: ORDERS
      - name: SHIPPERS
      - name: CUSTOMERS

